보통 강남의 집값은 학군지의 성격도 강하다는 것을 알 수 있다.

그렇다면 타 지역의 경우에도 학원 수가 많은 곳이 집값이 더 좋을까??

이러한 상관관계를 알아보고자 하였다

In [9]:
import warnings
warnings.filterwarnings(action='ignore')
%config Computer.use_jedi = False
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'D2Coding'
plt.rcParams['font.size'] = 15
import seaborn as sns
from plotnine import *
import missingno as msno
import folium

In [10]:
df = pd.read_csv('./data/프로젝트(학원).csv')
df

법정동  학원 개수  1제곱킬로미터당 학원 수  제곱미터당 가격(만원)
0     대치동    701          193.0        2413.0
1      목동    327           72.0        1674.0
2     신정동    230           54.0        1497.0
3     중계동    194           21.0        1153.0
4     반포동    147           30.0        3752.0
..    ...    ...            ...           ...
148   창신동      2            1.0        1231.0
149   이화동      2            2.0         435.0
150   수서동      1            1.0        2625.0
151   황학동      1            1.0        1021.0
152  가리봉동      1            2.0         821.0

[153 rows x 4 columns]

In [11]:
df_park = pd.read_csv('./data/법정동공원면적.csv')
df_park

법정동        공원면적
0      항동  10691299.0
1     도봉동   8822249.0
2     오류동   7894253.0
3     상계동   6953166.5
4     온수동   5717815.0
..    ...         ...
269  서소문동       397.5
270    합동       381.3
271   당인동       301.0
272   신창동       257.0
273   인사동       219.9

[274 rows x 2 columns]

In [12]:
df_school = pd.read_csv('./data/법정동학교수.csv')
df_school

Unnamed: 0  법정동  개수
0             0  가양동   3
1             1  갈현동   5
2             2  강일동   1
3             3  개포동   3
4             4  거여동   2
..          ...  ...  ..
150         150  화곡동   2
151         151  화양동   1
152         152  회기동   2
153         153  휘경동   3
154         154  흥인동   1

[155 rows x 3 columns]

In [14]:
width = pd.read_csv('./data/법정동면적.csv')
width

Unnamed: 0   법정동  학원 개수  1제곱킬로미터당 학원 수  제곱미터당 가격(만원)
0             0   대치동    701          193.0        2413.0
1             1    목동    327           72.0        1674.0
2             2   신정동    230           54.0        1497.0
3             3   중계동    194           21.0        1153.0
4             4   반포동    147           30.0        3752.0
..          ...   ...    ...            ...           ...
148         148   창신동      2            1.0        1231.0
149         149   이화동      2            2.0         435.0
150         150   수서동      1            1.0        2625.0
151         151   황학동      1            1.0        1021.0
152         152  가리봉동      1            2.0         821.0

[153 rows x 5 columns]

In [17]:
# 'grouped_df'와 'result' 데이터프레임을 '법정동'을 기준으로 이너 조인
merged_df = pd.merge(grouped_df, result, on='법정동', how='inner')

NameError: name 'grouped_df' is not defined

In [15]:
import warnings
warnings.filterwarnings(action='ignore')
%config Completer.use_jedi = False
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
import pandas as pd

Instructions for updating:
non-resource variables are not supported in the long term


In [21]:
data = df
data

법정동  학원 개수  1제곱킬로미터당 학원 수  제곱미터당 가격(만원)
0     대치동    701          193.0        2413.0
1      목동    327           72.0        1674.0
2     신정동    230           54.0        1497.0
3     중계동    194           21.0        1153.0
4     반포동    147           30.0        3752.0
..    ...    ...            ...           ...
148   창신동      2            1.0        1231.0
149   이화동      2            2.0         435.0
150   수서동      1            1.0        2625.0
151   황학동      1            1.0        1021.0
152  가리봉동      1            2.0         821.0

[153 rows x 4 columns]

In [26]:
# 법정동을 원-핫 인코딩
one_hot_encoded = pd.get_dummies(df, columns=['법정동'])
one_hot_encoded

학원 개수  1제곱킬로미터당 학원 수  제곱미터당 가격(만원)  법정동_가락동  법정동_가리봉동  법정동_가산동  법정동_가양동  \
0      701          193.0        2413.0        0         0        0        0   
1      327           72.0        1674.0        0         0        0        0   
2      230           54.0        1497.0        0         0        0        0   
3      194           21.0        1153.0        0         0        0        0   
4      147           30.0        3752.0        0         0        0        0   
..     ...            ...           ...      ...       ...      ...      ...   
148      2            1.0        1231.0        0         0        0        0   
149      2            2.0         435.0        0         0        0        0   
150      1            1.0        2625.0        0         0        0        0   
151      1            1.0        1021.0        0         0        0        0   
152      1            2.0         821.0        0         1        0        0   

     법정동_갈현동  법정동_개봉동  법정동_개포동  ...  법정동_한남동  법정동_합정동  법정동_항동  법정동_홍은동  \
0          0        0        0  ...        0        0       0        0   
1          0        0        0  ...        0        0       0        0   
2          0        0        0  ...        0        0       0        0   
3          0        0        0  ...        0        0       0        0   
4          0        0        0  ...        0        0       0        0   
..       ...      ...      ...  ...      ...      ...     ...      ...   
148        0        0        0  ...        0        0       0        0   
149        0        0        0  ...        0        0       0        0   
150        0        0        0  ...        0        0       0        0   
151        0        0        0  ...        0        0       0        0   
152        0        0        0  ...        0        0       0        0   

     법정동_홍제동  법정동_화곡동  법정동_화양동  법정동_황학동  법정동_효창동  법정동_후암동  
0          0        0        0        0        0        0  
1          0        0        0        0        0        0  
2          0        0        0        0        0        0  
3          0        0        0        0        0        0  
4          0        0        0        0        0        0  
..       ...      ...      ...      ...      ...      ...  
148        0        0        0        0        0        0  
149        0        0        0        0        0        0  
150        0        0        0        0        0        0  
151        0        0        0        1        0        0  
152        0        0        0        0        0        0  

[153 rows x 156 columns]

In [23]:
# 데이터프레임을 넘파이 배열로 변환
numpy_array = one_hot_encoded.to_numpy()
numpy_array

array([[7.010e+02, 1.930e+02, 2.413e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [3.270e+02, 7.200e+01, 1.674e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.300e+02, 5.400e+01, 1.497e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [1.000e+00, 1.000e+00, 2.625e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.000e+00, 1.000e+00, 1.021e+03, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [1.000e+00, 2.000e+00, 8.210e+02, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [35]:
# 넘파이 배열에서 변화 요인(피쳐) 데이터(평균 기온, 최저 기온, 최고 기온, 강수량)로 사용할 데이터를 뽑아낸다. 
xData = numpy_array[:, 1]
print(type(xData))
xData

<class 'numpy.ndarray'>


array([[193.],
       [ 72.],
       [ 54.],
       [ 21.],
       [ 30.],
       [ 23.],
       [  9.],
       [  6.],
       [ 11.],
       [ 29.],
       [ 11.],
       [ 15.],
       [ 38.],
       [ 14.],
       [ 25.],
       [142.],
       [  6.],
       [ 23.],
       [  8.],
       [ 45.],
       [ 20.],
       [ 36.],
       [ 12.],
       [  8.],
       [ 36.],
       [  7.],
       [  7.],
       [ 13.],
       [ 69.],
       [ 12.],
       [ 69.],
       [ 22.],
       [  7.],
       [ 19.],
       [ 21.],
       [  5.],
       [ 15.],
       [  8.],
       [ 14.],
       [ 51.],
       [  8.],
       [ 40.],
       [  3.],
       [  7.],
       [  7.],
       [  6.],
       [ 12.],
       [ 35.],
       [ 52.],
       [ 26.],
       [ 11.],
       [  4.],
       [ 25.],
       [ 14.],
       [ 18.],
       [ 16.],
       [  3.],
       [ 11.],
       [ 31.],
       [  6.],
       [  8.],
       [  5.],
       [  7.],
       [ 11.],
       [  9.],
       [  3.],
       [ 3

In [36]:
# 넘파이 배열에서 결과(타겟) 데이터(평균 가격)로 사용할 데이터를 뽑아낸다. 
yData = numpy_array[:, 2]
# yData.reshape(-1, 1) # 위의 변화요인과 차원을 맞춰주어야 한다. 
# yData = data[:, 5:6] # 슬라이싱 이용
yData = numpy_array[:, [2]] # 인덱싱으로 뽑아낸 결과를 리스트화 시켜도 2차원 형태의 데이터로 뽑아낸다.
yData

array([[2413.],
       [1674.],
       [1497.],
       [1153.],
       [3752.],
       [1649.],
       [1089.],
       [1103.],
       [ 838.],
       [1603.],
       [1694.],
       [2026.],
       [1256.],
       [2708.],
       [3154.],
       [3733.],
       [ 975.],
       [1549.],
       [1001.],
       [1066.],
       [1183.],
       [1842.],
       [1066.],
       [ 928.],
       [1303.],
       [1402.],
       [3028.],
       [1903.],
       [1100.],
       [2362.],
       [2175.],
       [ 850.],
       [1547.],
       [ 861.],
       [ 649.],
       [1898.],
       [ 646.],
       [ 776.],
       [1679.],
       [1541.],
       [1201.],
       [ 927.],
       [1102.],
       [ 840.],
       [ 932.],
       [ 843.],
       [1226.],
       [2252.],
       [1383.],
       [1668.],
       [ 962.],
       [1132.],
       [1364.],
       [1226.],
       [1347.],
       [ 775.],
       [1169.],
       [1874.],
       [1882.],
       [1113.],
       [1105.],
       [ 966.],
       [

In [46]:
# 뽑아낸 데이터를 텐서플로우에서 처리하기 위해서 placeholder를 만든다.
X = tf.placeholder(dtype=tf.float32, shape=[None, 1]) # 변화 요인을 기억할 placeholder
Y = tf.placeholder(dtype=tf.float32, shape=[None, 1]) # 결과 요인을 기억할 placeholder

In [47]:
# 다변인 선형 회귀 모델의 기울기(가중치)와 y 절편(바이어스)를 임의의 값으로 초기화한다. 
a = tf.Variable(tf.random_uniform([1, 1]), dtype=tf.float32) # 기울기, 내적을 하기 위해 4행 1열의 난수를 발생시킨다. 
b = tf.Variable(tf.random_uniform([1]), dtype=tf.float32) # y절편
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print('가중치\n', sess.run(a), sep='')
print('y절편\n', sess.run(b), sep='')

가중치
[[0.9482833]]
y절편
[0.2723428]


In [48]:
# 행렬의 곱셉(내적)을 이용해서 다변인 선형 회귀 모델의 가설로 사용할 식을 만든다 => 예측값을 계산하는 식
y = tf.matmul(X, a) + b # 예측값
# 오차(비용) 함수를 만든다. => 평균 제곱법 => 예측값(y)과 실제값(Y)의 편차에 제곱에 대한 평균
loss = tf.reduce_mean(tf.square(y - Y))
# 경사 하강법 알고리즘을 사용해서 오차 함수의 결과를 최소로 하는 기울기와 y절편을 찾는다. 
gradient_descent = tf.train.GradientDescentOptimizer(0.001).minimize(loss)

In [49]:
# 학습 시킨다.
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for epoch in range(100001):
    _, loss_, y_ = sess.run([gradient_descent, loss, y], feed_dict={X: xData, Y: yData})
    if epoch % 5000 == 0:
        # print('epoch: %6d, loss: %12.3f, price: %8.2f' % (epoch, loss_, y_[0]))
        print('epoch: {:6d}, loss: {:12.3f}, price: {:8.2f}'.format(epoch, loss_, y_[0][0]))

epoch:      0, loss:  2234493.000, price:    39.67
epoch:   5000, loss:   292810.625, price:  2938.43
epoch:  10000, loss:   292809.000, price:  2933.77
epoch:  15000, loss:   292809.000, price:  2933.77
epoch:  20000, loss:   292809.000, price:  2933.77
epoch:  25000, loss:   292809.000, price:  2933.77
epoch:  30000, loss:   292809.000, price:  2933.77
epoch:  35000, loss:   292809.000, price:  2933.77
epoch:  40000, loss:   292809.000, price:  2933.77
epoch:  45000, loss:   292809.000, price:  2933.77
epoch:  50000, loss:   292809.000, price:  2933.77
epoch:  55000, loss:   292809.000, price:  2933.77
epoch:  60000, loss:   292809.000, price:  2933.77
epoch:  65000, loss:   292809.000, price:  2933.77
epoch:  70000, loss:   292809.000, price:  2933.77
epoch:  75000, loss:   292809.000, price:  2933.77
epoch:  80000, loss:   292809.000, price:  2933.77
epoch:  85000, loss:   292809.000, price:  2933.77
epoch:  90000, loss:   292809.000, price:  2933.77
epoch:  95000, loss:   292809.0

In [52]:
# 테스트
data = [[25]]
result = sess.run(y, feed_dict={X: data})
print(result)
print('1(㎢)당 학원 개수가 : {:4.1f}일 때 '\
      '예상 집값은 면적(㎡)당 {:7,.2f}만원 입니다.'.format(data[0][0], result[0][0]))

[[1464.8049]]
1(㎢)당 학원 개수가 : 25.0일 때 예상 집값은 면적(㎡)당 1,464.80만원 입니다.
